name: SonarQube CI Pipeline

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: "8.9"
    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: 'Run SonarQube'
      run: |
        sudo apt-get install unzip
        unzip sonar-application/build/distributions/sonar-application-25.2-SNAPSHOT.zip
        sonar-application/build/distributions/sonarqube-25.2-SNAPSHOT/bin/linux-x86-64/sonar.sh start

